# Generated by Django 2.1 on 2019-04-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mem',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='mems'),
        ),
    ]
