# Generated by Django 2.1 on 2019-05-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_mem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
